name: Build site
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: divvun/lt-support

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Convert yaml to inline html
        run: ./insert-tables.sh
        shell: bash

      - name: deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          enable_jekyll: true
